config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	
  resources :users,only: [:show,:index,:edit,:update]
  
  resources :books do
  	# ↓いいねは1つのbookに対して1回しか行わないためresource(単数形)
  	resource :favorites,only: [:create, :destroy]
  	# ↓コメントは1つのbookに対して複数回行うためresources(複数形)
  	resources :book_comments,only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'

end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments,dependent: :destroy

	# def favorited_by?(user)
	# 	favorites.where(user_id: user.id).exists?
	# end

	# ↓Bookに対して、favoriteがあるかどうかを絞りこませる
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
  	@showbook = Book.find(params[:id])
    @book = Book.new
    @user = @showbook.user
    @book_comment = BookComment.new
    @book_comments = BookComment.where(book_id: @showbook)
  end

  def index
  	@books = Book.all#一覧表示するためにBookモデルの情報を全てくださいのall
    # @showbook = @books.find(params[:id])
    @book = Book.new
    @user = current_user
    @favorite = Favorite.new
  end

  def create
    # p "newbookだよ"
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @user = current_user
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

      def correct_user
        @book = Book.find(params[:id])
        @user = @book.user
        if current_user != @user
          redirect_to books_path
        end
      end

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<!-- <div class="row"> -->
<!-- <div class="col-xs-3"> -->
<h2>New book</h2>
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

<!-- </div> -->
<!-- </div> -->

app/views/books/edit.html.erb
  <% if @book.errors.any? %>
    <div class="error">
      <p class="error-top">
        <%= pluralize(@book.errors.count, "error") %>
        prohibited this book from being saved:
      </p>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
  <% if @book.errors.any? %>
    <div class="error">
      <p class="error-top">
        <%= pluralize(@book.errors.count, "error") %>
        prohibited this book from being saved:
      </p>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<!-- <h2>New book</h2> -->
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
					<th></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					

					<% if book.favorited_by?(current_user) %>
					  <td>
					    <%= link_to book_favorites_path(book), method: :delete do %>
					      <!-- <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i> -->
					      <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
					      <%= book.favorites.count %>
					    <% end %>
					  </td>
					<% else %>
					  <td>
					    <%# link_to book_favorites_path(:book_id), method: :post do %>
					    <%= link_to book_favorites_path(book), method: :post do %>
					      <!-- <i class="fa fa-heart-o" aria-hidden="true"></i> -->
					      <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
					      <%= book.favorites.count %>
					    <% end %>
					  </td>
					<% end %>
					<td>コメント数: <%= book.book_comments.count %></td>
					

				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@user) do %>
						<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @user.name %>
						<% end %>
					</td>

					
					<td><%= link_to @showbook.title, @book %></td>
					<td><%= @showbook.body %></td>


					<% if @showbook.favorited_by?(current_user) %>
					  <td>
					    <%= link_to book_favorites_path(@showbook), method: :delete do %>
					      <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
					      <%= @showbook.favorites.count %>
					    <% end %>
					  </td>
					<% else %>
					  <td>
					    <%= link_to book_favorites_path(@showbook), method: :post do %>
					      <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
					      <%= @showbook.favorites.count %>
					    <% end %>
					  </td>
					<% end %>

					<td>コメント数: <%= @showbook.book_comments.count %></td>


					<% if @showbook.user == current_user %>
					<td><%= link_to "Edit",edit_book_path(@showbook), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@showbook, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@showbook.id}" %></td>
					<% end %>

				</tr>
			</table>


			<!-- ↓コメント -->
			<table>
				<% @book_comments.each do |book_comments| %>
				<tr>
					<th>
						<%= book_comments.user.name %>
					</th>
				</tr>
				<tr>
					<td class="col-xs-3">
						<%= book_comments.comment %>
					</td>
					<% if book_comments.user == current_user %>
					<td><%= link_to "Destroy",book_book_comment_path(@showbook,book_comments), method: :delete, class: "btn-sm btn-danger" %>
					</td>
					<% end %>
				</tr>
				<% end %>
			</table>

			<table>
				<tr>
				<%= form_for [@showbook, @book_comment] do |f| %>
					<%= f.text_area :comment, class: "col-xs-6" %>
					<%= f.submit "送信" %>
				</tr>
				<% end %>

			</table>

	</div>
</div>